# INDENT IN SO IMPORTANT ,SPACES AND ENTER

#if you want to change  the server port in application.yml use this format
#server:
#  port: 800

# I use this site to convert the properties to yml format :https://www.javainuse.com/app2yaml


#this is stored value you can import that by @Value("${welcome.message}") IN .uml
#welcome:
#  message: hello this is from another file

spring:
  profile:
    active: dev
#3 --- is required for separating  profile

---
#h2 database
#it checked by insomnia and it was OK
spring:
  profile: dev
  datasource:
    driverClassName: org.h2.Driver
    password: 1235
    url: jdbc:h2:mem:dcbapp-dev
    username: sdr
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


---
#h2 database
#it checked by insomnia and it was OK
spring:
  profile: qa
  datasource:
    driverClassName: org.h2.Driver
    password: 1235
    url: jdbc:h2:mem:dcbapp-qa
    username: sdr
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

#for creating end point use this
management:
  endpoint:
    web:
      exposure:
        include: "*"
#        exclude: qa     if you want to hide from end point do this
#---
#
#spring:
#  profile: qa
#  datasource:
#    driverClassName: org.h2.Driver
#    password: 1235
#    url: jdbc:h2:mem:dcbapp-qa
#    username: sdr
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#
#---
#spring:
#  profile: prod
#  datasource:
#    driverClassName: org.h2.Driver
#    password: 1235
#    url: jdbc:h2:mem:dcbapp-prod
#    username: sdr
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#

#my sql database // but it is not working
#---
#spring:
#  profile: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: admin
#    url: jdbc:mysql://localhost:3306/dcbapp
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
